### PR TITLE
Add `twilio` to the platform enums

### PR DESCRIPTION
**Pull request by kolanos**
I'm not sure if there are other possible values here, but I'm seeing this one in the wild.

### CODE REVIEW

**Comment by kolanos** [comment]
This is meant to fix smooch/smooch-python#2.

**Comment by alavers** [comment]
Thanks for the PR! The full set of possible values here are:

```
- ios
- android
- web
- twilio
- telegram
- messenger
- frontendEmail
- line
- wechat
- viber
- twitter
- mailgun
- other
```

**Comment by kolanos** [comment]
@alavers Ok, added.

**Comment by alavers** [comment]
Sorry I was mistaken, this spec repo is actually generated from an internal spec definition. I've gone ahead and applied your changes there. You should find them in the latest client library version (1.5)

**Pull request closed without merging**
